#!/usr/bin/env bash
# claude_here egress allowlist, run by the root phase of the entrypoint before
# it drops to the sandbox user.
#
# dnsmasq becomes the container resolver and adds every address it answers for
# an allowlisted name to the `ch_allow` ipset; iptables then permits exactly
# those destinations and rejects the rest. Nothing is intercepted and no
# certificate is injected, so TLS stays end to end — and unlike a proxy this
# works for clients that ignore http_proxy (Maven and Gradle among them).
#
# $1: comma separated list of allowed domains. Subdomains are included.
set -eu
DOMAINS="${1:-}"
SET4=ch_allow
SET6=ch_allow6
CONF=/etc/dnsmasq.d/claude_here.conf  # must end in .conf: see conf-dir in the base image

if [ -z "${DOMAINS}" ]; then
  echo "claude_here: net allowlist requested but the list is empty" >&2
  exit 1
fi

# Upstream resolvers as docker handed them to us, before we take over resolv.conf.
upstream="$(awk '/^nameserver/ {print $2}' /etc/resolv.conf | head -3)"
if [ -z "${upstream}" ]; then
  upstream=127.0.0.11
fi

ipset create "${SET4}" hash:ip family inet timeout 3600 -exist
ipset create "${SET6}" hash:ip family inet6 timeout 3600 -exist

{
  echo "# generated by claude_here; do not edit"
  echo "no-resolv"
  for u in ${upstream}; do echo "server=${u}"; done
  echo "listen-address=127.0.0.1"
  echo "bind-interfaces"
  echo "no-hosts"
  echo "cache-size=1000"
  # One ipset line per domain: dnsmasq matches the name and every subdomain.
  printf '%s\n' "${DOMAINS}" | tr ',' '\n' | while read -r d; do
    [ -n "${d}" ] || continue
    echo "ipset=/${d}/${SET4},${SET6}"
  done
} > "${CONF}"

# dnsmasq must answer before anything resolves through it.
dnsmasq --conf-file=/etc/dnsmasq.conf --user=dnsmasq --group=nogroup
printf 'nameserver 127.0.0.1\noptions ndots:0\n' > /etc/resolv.conf

filter() {
  local cmd="$1" set="$2"
  "${cmd}" -N CLAUDE_HERE_OUT 2>/dev/null || "${cmd}" -F CLAUDE_HERE_OUT
  "${cmd}" -A CLAUDE_HERE_OUT -o lo -j ACCEPT
  "${cmd}" -A CLAUDE_HERE_OUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  # The capture and the resolver keep working whatever the sandbox user does.
  "${cmd}" -A CLAUDE_HERE_OUT -m owner --uid-owner dnsmasq -j ACCEPT
  "${cmd}" -A CLAUDE_HERE_OUT -m set --match-set "${set}" dst -j ACCEPT
  "${cmd}" -A CLAUDE_HERE_OUT -j REJECT --reject-with icmp-admin-prohibited
  "${cmd}" -C OUTPUT -j CLAUDE_HERE_OUT 2>/dev/null ||
    "${cmd}" -A OUTPUT -j CLAUDE_HERE_OUT
}

filter iptables "${SET4}"
# IPv6 is rejected wholesale when ip6tables is unavailable; a missing rule must
# never mean "allowed".
if command -v ip6tables >/dev/null 2>&1; then
  ip6tables -N CLAUDE_HERE_OUT 2>/dev/null || ip6tables -F CLAUDE_HERE_OUT
  ip6tables -A CLAUDE_HERE_OUT -o lo -j ACCEPT
  ip6tables -A CLAUDE_HERE_OUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  ip6tables -A CLAUDE_HERE_OUT -m owner --uid-owner dnsmasq -j ACCEPT
  ip6tables -A CLAUDE_HERE_OUT -m set --match-set "${SET6}" dst -j ACCEPT
  ip6tables -A CLAUDE_HERE_OUT -j REJECT --reject-with adm-prohibited
  ip6tables -C OUTPUT -j CLAUDE_HERE_OUT 2>/dev/null ||
    ip6tables -A OUTPUT -j CLAUDE_HERE_OUT
fi

count="$(printf '%s\n' "${DOMAINS}" | tr ',' '\n' | grep -c . || true)"
echo "claude_here: egress allowlist active (${count} domain(s)); everything else is rejected" >&2
