//! The bundled claude_here plugin: the skills that are specific to running in
//! this sandbox, plus the language server declarations of the enabled
//! toolchains. Generated on the host from the registry, mounted read-only, and
//! registered inside the container by the entrypoint — so no marketplace has to
//! be fetched over the network, and Dart gets a language server although no
//! official plugin exists for it (ADR 0008).

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde_json::{Map, Value, json};

use crate::image::hash_inputs;
use crate::toolchain::Toolchain;

/// Marketplace and plugin name.
pub const MARKETPLACE: &str = "claude_here";
/// Plugin name inside that marketplace.
pub const PLUGIN: &str = "claude-here";
/// Container path the generated directory is mounted at, relative to the
/// container home.
pub const CONTAINER_DIR: &str = ".claude_here/plugin";

/// One bundled skill: directory name and `SKILL.md` body.
const SKILLS: &[(&str, &str)] = &[
    ("ro-handoff", include_str!("../images/skills/ro-handoff.md")),
    (
        "diagram-loop",
        include_str!("../images/skills/diagram-loop.md"),
    ),
    ("net-triage", include_str!("../images/skills/net-triage.md")),
];

/// `lspServers` for the enabled toolchains, in the shape the marketplace
/// manifest uses.
fn lsp_servers(chain: &[&Toolchain]) -> Map<String, Value> {
    let mut servers = Map::new();
    for t in chain {
        for l in t.lsp {
            let mut ext = Map::new();
            for (suffix, language) in l.extensions {
                ext.insert(
                    (*suffix).to_string(),
                    Value::String((*language).to_string()),
                );
            }
            let mut entry = Map::new();
            entry.insert("command".into(), Value::String(l.command.to_string()));
            if !l.args.is_empty() {
                entry.insert(
                    "args".into(),
                    Value::Array(
                        l.args
                            .iter()
                            .map(|a| Value::String((*a).to_string()))
                            .collect(),
                    ),
                );
            }
            entry.insert("extensionToLanguage".into(), Value::Object(ext));
            servers.insert(l.name.to_string(), Value::Object(entry));
        }
    }
    servers
}

/// The marketplace manifest carrying the single bundled plugin.
fn marketplace_json(chain: &[&Toolchain]) -> Value {
    let mut plugin = json!({
        "name": PLUGIN,
        "description": "Skills and language servers for working inside a claude_here sandbox",
        "version": env!("CARGO_PKG_VERSION"),
        "source": "./",
        "category": "development",
    });
    let servers = lsp_servers(chain);
    if !servers.is_empty()
        && let Some(obj) = plugin.as_object_mut()
    {
        obj.insert("lspServers".into(), Value::Object(servers));
    }
    json!({
        "name": MARKETPLACE,
        "description": "Generated by claude_here for this session",
        "owner": {"name": "claude_here"},
        "plugins": [plugin],
    })
}

fn plugin_json() -> Value {
    json!({
        "name": PLUGIN,
        "description": "Skills and language servers for working inside a claude_here sandbox",
        "version": env!("CARGO_PKG_VERSION"),
    })
}

/// Everything that goes into the directory, as `(relative path, contents)`.
fn files(chain: &[&Toolchain]) -> Result<Vec<(PathBuf, String)>> {
    let mut out = vec![
        (
            PathBuf::from(".claude-plugin").join("marketplace.json"),
            serde_json::to_string_pretty(&marketplace_json(chain))
                .context("serializing marketplace.json")?,
        ),
        (
            PathBuf::from(".claude-plugin").join("plugin.json"),
            serde_json::to_string_pretty(&plugin_json()).context("serializing plugin.json")?,
        ),
    ];
    for (name, body) in SKILLS {
        out.push((
            PathBuf::from("skills").join(name).join("SKILL.md"),
            (*body).to_string(),
        ));
    }
    Ok(out)
}

/// Write the directory if its contents changed and return its hash. The hash is
/// also written to `.hash`, which the entrypoint uses to decide whether the
/// plugin has to be registered again.
pub fn generate(dir: &Path, chain: &[&Toolchain]) -> Result<String> {
    let files = files(chain)?;
    let parts: Vec<&str> = files.iter().map(|(_, body)| body.as_str()).collect();
    let hash = hash_inputs(&parts);
    let marker = dir.join(".hash");
    if fs::read_to_string(&marker).is_ok_and(|h| h.trim() == hash) {
        return Ok(hash);
    }
    for (rel, body) in &files {
        let path = dir.join(rel);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
        }
        fs::write(&path, body).with_context(|| format!("writing {}", path.display()))?;
    }
    fs::write(&marker, format!("{hash}\n"))
        .with_context(|| format!("writing {}", marker.display()))?;
    Ok(hash)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::toolchain;

    #[test]
    fn declares_a_server_for_every_toolchain_that_has_one() {
        let chain = toolchain::resolve(&["rust".into(), "dart".into()]).unwrap_or_default();
        let servers = lsp_servers(&chain);
        assert_eq!(servers["rust-analyzer"]["command"], "rust-analyzer");
        assert_eq!(
            servers["rust-analyzer"]["extensionToLanguage"][".rs"],
            "rust"
        );
        // Dart has no official plugin; the args carry the protocol switch.
        assert_eq!(servers["dart"]["command"], "dart");
        assert_eq!(servers["dart"]["args"][0], "language-server");
        assert!(servers.get("gopls").is_none());
    }

    #[test]
    fn no_toolchain_means_no_lsp_block_but_still_a_plugin() {
        let m = marketplace_json(&[]);
        assert_eq!(m["name"], MARKETPLACE);
        assert_eq!(m["plugins"][0]["name"], PLUGIN);
        assert!(m["plugins"][0].get("lspServers").is_none());
    }

    #[test]
    fn generate_is_idempotent_and_hash_follows_the_toolchains() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let rust = toolchain::resolve(&["rust".into()]).unwrap_or_default();
        let a = generate(dir.path(), &rust)?;
        let b = generate(dir.path(), &rust)?;
        assert_eq!(a, b);
        assert!(dir.path().join("skills/ro-handoff/SKILL.md").exists());
        let text = fs::read_to_string(dir.path().join(".claude-plugin/marketplace.json"))?;
        assert!(text.contains("rust-analyzer"));
        let c = generate(
            dir.path(),
            &toolchain::resolve(&["go".into()]).unwrap_or_default(),
        )?;
        assert_ne!(a, c);
        Ok(())
    }

    #[test]
    fn every_skill_has_frontmatter_with_a_description() {
        for (name, body) in SKILLS {
            assert!(body.starts_with("---\n"), "{name} has no frontmatter");
            assert!(
                body.contains("\ndescription: "),
                "{name} has no description"
            );
        }
    }
}
